[package]
name = "aht20-rs"
version = "0.1.1"
authors = ["QuackHack-McBlindy"]
license = "MIT"
description = "Bare Metal no_std librarry for AHT20 written in Rust"
repository = "https://github.com/QuackHack-McBlindy/no_std_components"
readme = "README.md"
keywords = ["esp-hal", "embedded", "esp32"]
categories = ["embedded"]
edition = "2024"

[dependencies]

embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-futures = "0.1"
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"

